[2025-01-31T22:16:42.360+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T22:16:42.407+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T22:15:00+00:00 [queued]>
[2025-01-31T22:16:42.426+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T22:15:00+00:00 [queued]>
[2025-01-31T22:16:42.427+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T22:16:42.469+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): stg-load> on 2025-01-31 22:15:00+00:00
[2025-01-31T22:16:42.484+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3466) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T22:16:42.487+0000] {standard_task_runner.py:72} INFO - Started process 3468 to run task
[2025-01-31T22:16:42.490+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'load_gener_data', 'stg-load', 'scheduled__2025-01-31T22:15:00+00:00', '--job-id', '669', '--raw', '--subdir', 'DAGS_FOLDER/DAG_test_data.py', '--cfg-path', '/tmp/tmpfc4jv762']
[2025-01-31T22:16:42.496+0000] {standard_task_runner.py:105} INFO - Job 669: Subtask stg-load
[2025-01-31T22:16:42.673+0000] {task_command.py:467} INFO - Running <TaskInstance: load_gener_data.stg-load scheduled__2025-01-31T22:15:00+00:00 [running]> on host a664bcf281bf
[2025-01-31T22:16:43.405+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='load_gener_data' AIRFLOW_CTX_TASK_ID='stg-load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T22:15:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T22:15:00+00:00'
[2025-01-31T22:16:43.407+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T22:16:43.698+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T22:16:43.886+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-31T22:16:43.933+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T22:16:43.934+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=load_gener_data, task_id=stg-load, run_id=scheduled__2025-01-31T22:15:00+00:00, execution_date=20250131T221500, start_date=20250131T221642, end_date=20250131T221643
[2025-01-31T22:16:44.021+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T22:16:44.081+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-31T22:16:44.084+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
