[2025-01-31T21:30:09.438+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-31T21:30:09.493+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_processing.nds-load scheduled__2025-01-31T21:28:00+00:00 [queued]>
[2025-01-31T21:30:09.515+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_processing.nds-load scheduled__2025-01-31T21:28:00+00:00 [queued]>
[2025-01-31T21:30:09.515+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 1
[2025-01-31T21:30:09.561+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): nds-load> on 2025-01-31 21:28:00+00:00
[2025-01-31T21:30:09.580+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=2751) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-31T21:30:09.583+0000] {standard_task_runner.py:72} INFO - Started process 2754 to run task
[2025-01-31T21:30:09.586+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'etl_processing', 'nds-load', 'scheduled__2025-01-31T21:28:00+00:00', '--job-id', '613', '--raw', '--subdir', 'DAGS_FOLDER/DAG_etl.py', '--cfg-path', '/tmp/tmpn48tb7ki']
[2025-01-31T21:30:09.592+0000] {standard_task_runner.py:105} INFO - Job 613: Subtask nds-load
[2025-01-31T21:30:09.724+0000] {task_command.py:467} INFO - Running <TaskInstance: etl_processing.nds-load scheduled__2025-01-31T21:28:00+00:00 [running]> on host a664bcf281bf
[2025-01-31T21:30:10.404+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='etl_processing' AIRFLOW_CTX_TASK_ID='nds-load' AIRFLOW_CTX_EXECUTION_DATE='2025-01-31T21:28:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-31T21:28:00+00:00'
[2025-01-31T21:30:10.407+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-31T21:30:10.470+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:10.537+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:10.713+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:10.916+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.080+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.193+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.328+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.480+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.672+0000] {base.py:84} INFO - Retrieving connection 'DB_connect'
[2025-01-31T21:30:11.812+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-31T21:30:11.856+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-31T21:30:11.857+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=etl_processing, task_id=nds-load, run_id=scheduled__2025-01-31T21:28:00+00:00, execution_date=20250131T212800, start_date=20250131T213009, end_date=20250131T213011
[2025-01-31T21:30:11.934+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-31T21:30:12.029+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-31T21:30:12.060+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
